/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package vistas;

/**
 *
 * @author Luis
 */
public class VistaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_principal = new javax.swing.JPanel();
        rbtn_ascendente = new javax.swing.JRadioButton();
        rbtn_descendente = new javax.swing.JRadioButton();
        combo_indices = new javax.swing.JComboBox();
        panel_interno = new javax.swing.JPanel();
        rbtn_insercion = new javax.swing.JRadioButton();
        rbtn_burbuja = new javax.swing.JRadioButton();
        rbtn_shellsort = new javax.swing.JRadioButton();
        rbtn_mergesort = new javax.swing.JRadioButton();
        rbtn_quicksort = new javax.swing.JRadioButton();
        panel_externo = new javax.swing.JPanel();
        rbtn_directa = new javax.swing.JRadioButton();
        rbtn_natural = new javax.swing.JRadioButton();
        panel_resultados = new javax.swing.JPanel();
        scrollpane_tabla = new javax.swing.JScrollPane();
        tabla_resultados = new javax.swing.JTable();
        lb_valor = new javax.swing.JLabel();
        tf_valor = new javax.swing.JTextField();
        lb_criterio_ordenamiento = new javax.swing.JLabel();
        btn_limpiar = new javax.swing.JButton();
        btn_buscar = new javax.swing.JButton();
        combo_signos = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel_principal.setBorder(javax.swing.BorderFactory.createTitledBorder("Índice"));

        rbtn_ascendente.setText("Ascendente");
        rbtn_ascendente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_ascendenteActionPerformed(evt);
            }
        });

        rbtn_descendente.setText("Descendente");

        combo_indices.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Índice Nacional de Precios al consumidor, Variación mensual" }));
        combo_indices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_indicesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_principalLayout = new javax.swing.GroupLayout(panel_principal);
        panel_principal.setLayout(panel_principalLayout);
        panel_principalLayout.setHorizontalGroup(
            panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_principalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_principalLayout.createSequentialGroup()
                        .addComponent(rbtn_ascendente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbtn_descendente)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(combo_indices, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        panel_principalLayout.setVerticalGroup(
            panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_principalLayout.createSequentialGroup()
                .addComponent(combo_indices, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtn_ascendente)
                    .addComponent(rbtn_descendente))
                .addContainerGap())
        );

        panel_interno.setBorder(javax.swing.BorderFactory.createTitledBorder("Ordenamiento interno"));

        rbtn_insercion.setText("Inserción");
        rbtn_insercion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_insercionActionPerformed(evt);
            }
        });

        rbtn_burbuja.setText("Burbuja");

        rbtn_shellsort.setText("ShellSort");

        rbtn_mergesort.setText("MergeSort");
        rbtn_mergesort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_mergesortActionPerformed(evt);
            }
        });

        rbtn_quicksort.setText("QuickSort");
        rbtn_quicksort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_quicksortActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_internoLayout = new javax.swing.GroupLayout(panel_interno);
        panel_interno.setLayout(panel_internoLayout);
        panel_internoLayout.setHorizontalGroup(
            panel_internoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_internoLayout.createSequentialGroup()
                .addComponent(rbtn_insercion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtn_burbuja)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtn_shellsort)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbtn_mergesort)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbtn_quicksort)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        panel_internoLayout.setVerticalGroup(
            panel_internoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_internoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(rbtn_insercion)
                .addComponent(rbtn_burbuja)
                .addComponent(rbtn_shellsort)
                .addComponent(rbtn_mergesort)
                .addComponent(rbtn_quicksort))
        );

        panel_externo.setBorder(javax.swing.BorderFactory.createTitledBorder("Ordenamiento externo"));

        rbtn_directa.setText("Directa");

        rbtn_natural.setText("Natural");
        rbtn_natural.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_naturalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_externoLayout = new javax.swing.GroupLayout(panel_externo);
        panel_externo.setLayout(panel_externoLayout);
        panel_externoLayout.setHorizontalGroup(
            panel_externoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_externoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbtn_directa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbtn_natural)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        panel_externoLayout.setVerticalGroup(
            panel_externoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_externoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(rbtn_directa)
                .addComponent(rbtn_natural))
        );

        panel_resultados.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultados"));

        tabla_resultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Valor del índice"
            }
        ));
        scrollpane_tabla.setViewportView(tabla_resultados);

        javax.swing.GroupLayout panel_resultadosLayout = new javax.swing.GroupLayout(panel_resultados);
        panel_resultados.setLayout(panel_resultadosLayout);
        panel_resultadosLayout.setHorizontalGroup(
            panel_resultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_resultadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollpane_tabla)
                .addContainerGap())
        );
        panel_resultadosLayout.setVerticalGroup(
            panel_resultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_resultadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollpane_tabla, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                .addContainerGap())
        );

        lb_valor.setText("Valor");

        lb_criterio_ordenamiento.setText("Criterio de ordenamiento");

        btn_limpiar.setText("Limpiar");

        btn_buscar.setText("Buscar");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        combo_signos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "=", ">", ">=", "<", "<=" }));
        combo_signos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_signosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_buscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_limpiar))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(panel_principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panel_resultados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(lb_valor)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tf_valor))
                                .addComponent(panel_interno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(panel_externo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lb_criterio_ordenamiento)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(combo_signos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(panel_principal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panel_interno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_externo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_valor)
                    .addComponent(tf_valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_criterio_ordenamiento)
                    .addComponent(combo_signos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panel_resultados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_limpiar)
                    .addComponent(btn_buscar))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtn_insercionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_insercionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtn_insercionActionPerformed

    private void rbtn_mergesortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_mergesortActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtn_mergesortActionPerformed

    private void rbtn_naturalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_naturalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtn_naturalActionPerformed

    private void rbtn_ascendenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_ascendenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtn_ascendenteActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void rbtn_quicksortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_quicksortActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtn_quicksortActionPerformed

    private void combo_indicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_indicesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_indicesActionPerformed

    private void combo_signosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_signosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_signosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_buscar;
    public javax.swing.JButton btn_limpiar;
    public javax.swing.JComboBox combo_indices;
    public javax.swing.JComboBox combo_signos;
    public javax.swing.JLabel lb_criterio_ordenamiento;
    public javax.swing.JLabel lb_valor;
    public javax.swing.JPanel panel_externo;
    public javax.swing.JPanel panel_interno;
    public javax.swing.JPanel panel_principal;
    public javax.swing.JPanel panel_resultados;
    public javax.swing.JRadioButton rbtn_ascendente;
    public javax.swing.JRadioButton rbtn_burbuja;
    public javax.swing.JRadioButton rbtn_descendente;
    public javax.swing.JRadioButton rbtn_directa;
    public javax.swing.JRadioButton rbtn_insercion;
    public javax.swing.JRadioButton rbtn_mergesort;
    public javax.swing.JRadioButton rbtn_natural;
    public javax.swing.JRadioButton rbtn_quicksort;
    public javax.swing.JRadioButton rbtn_shellsort;
    private javax.swing.JScrollPane scrollpane_tabla;
    public javax.swing.JTable tabla_resultados;
    public javax.swing.JTextField tf_valor;
    // End of variables declaration//GEN-END:variables
}
